export const GET_CHARACTERES_RESQUESTED = 'GET_CHARACTERES_REQUESTED'; 
export const GET_CHARACTERES_SUCCESS = 'GET_CHARACTERES_SUCCESS'; 
export const GET_CHARACTERES_FAILED = 'GET_CHARACTERES_FAILED'; 